// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFNFwEeZdBoqhpyJg7dXM6QMh3OS5c70Q',
    appId: '1:1028133709956:web:8ec09f68827117ed757ad1',
    messagingSenderId: '1028133709956',
    projectId: 'queries-firebase',
    authDomain: 'queries-firebase.firebaseapp.com',
    storageBucket: 'queries-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOAkVm3PujqCfr7qOSPJdKYlCWMkk5Zg',
    appId: '1:1028133709956:android:bd72364e832eda80757ad1',
    messagingSenderId: '1028133709956',
    projectId: 'queries-firebase',
    storageBucket: 'queries-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbU9A2hyS1m6OyhCaGANE7F4H2YaCgH04',
    appId: '1:1028133709956:ios:66d2b8cfb5b19526757ad1',
    messagingSenderId: '1028133709956',
    projectId: 'queries-firebase',
    storageBucket: 'queries-firebase.appspot.com',
    iosBundleId: 'com.example.queriesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbU9A2hyS1m6OyhCaGANE7F4H2YaCgH04',
    appId: '1:1028133709956:ios:854de538d8b31aee757ad1',
    messagingSenderId: '1028133709956',
    projectId: 'queries-firebase',
    storageBucket: 'queries-firebase.appspot.com',
    iosBundleId: 'com.example.queriesFirebase.RunnerTests',
  );
}
