name: info_lugar
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bali_beach.jpg
    - assets/images/sm.jpeg
    - assets/images/nd.jpeg
    - assets/images/ne.jpeg
    - assets/images/os.jpeg
    - assets/images/co.jpeg

  fonts:
    - family: BlackOpsOne
      fonts:
        - asset: assets/fonts/BlackOpsOne-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

